name: Salesforce B2B-QA Deployment

on:
  
  push:
    branches:
      - 'featureTQA/**'

jobs:
  b2b_qa_deployment:
    runs-on: ubuntu-latest
    environment: QA_SECRET
    steps:
      # Install Salesforce CLI
      - name: "Install Salesforce CLI"
        run: |
          npm install @salesforce/cli --location=global
          nodeInstallPath=$(npm config get prefix)
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH
          sf --version
      # Install SGD Plugin
      - name: "Install SGD Plugin"
        # run: "sf plugins install sfdx-git-delta --help"
        run: |
          echo y | sf plugins install sfdx-git-delta
          sfdx plugins
      # Install utilities
      - name: Install utilities
        run: |
         pip install yq
         xq --version
      # Checkout the code in the pull request
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Authenticate to target org
      - name: "Authenticate to Org"
        env:
          QA_SECRET: ${{ secrets.QA_SECRET}}
        run: |
          echo "$QA_SECRET" > ./SFDX_URL.txt
          sf org login sfdx-url --set-default -f ./SFDX_URL.txt
          sf org list
      # Delta deploy
      - name: "Delta deploy"
        run: |
          sf sgd source delta --to "HEAD" --from "origin/QAN" --output "." -i .forceignore
          echo "--- package.xml generated with added and modified metadata ---"
          cat package/package.xml
          echo
          echo "--- Delta Deploy ---"  
          sf project deploy start -x package/package.xml
