name: Nani Org Sample Validation

on:
  push:
    branches:
      - 'featureQA/**'

jobs:
  Nani_Org_Sample_Validation:
    runs-on: ubuntu-latest
    environment: QA_SECRET
    steps:
      # Install Salesforce CLI
      - name: "Install Salesforce CLI"
        run: |
          npm install @salesforce/cli --location=global
          nodeInstallPath=$(npm config get prefix)
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH
          sf --version
      # Install SGD plugin for delta package
      - name: "Install SGD Plugin"
        # run: "sf plugins install sfdx-git-delta --help"
        run: |
          echo y | sf plugins install sfdx-git-delta
          sfdx plugins
      # Install utilities
      - name: Install utilities
        run: |
         pip install yq
         xq --version
      # checkout the code in the feature branch 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Authenticate the target org for validation and deployment
      - name: "Authentication to target Org"
        env:
          QA_SECRET: ${{ secrets.QA_SECRET}}
        run: |
          echo "$QA_SECRET" > ./SFDX_URL.txt
          sf org login sfdx-url --set-default -f ./SFDX_URL.txt
          sf org list
      # Delta package deployment
      - name: "Delta Deploy"
        run: |
          sf sgd source delta --to "HEAD" --from "origin/QAN" --output "." -i .forceignore
          echo "---package.xml generated with added and modified metadata---"
          cat package/package.xml
          echo
          sf project deploy validate -x package/package.xml